# Generated by Django 5.2.7 on 2025-10-22 16:51

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='short_bio',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Short professional summary or about text'),
        ),
    ]
