# Generated by Django 5.2.7 on 2025-10-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_profile_cv_alter_profile_facebook_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('skill_type', models.CharField(choices=[('technical', 'Technical'), ('soft', 'Soft')], default='technical', max_length=20)),
                ('proficiency', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(blank=True, help_text='Optional group like Frontend, Backend, QA, etc.', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('icon', models.CharField(blank=True, help_text='Optional: store icon class (e.g. fa-python, devicon-django-plain)', max_length=50)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['order', 'name'],
            },
        ),
    ]
