# Generated by Django 5.2.7 on 2025-10-22 17:23

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('company_website', models.URLField(blank=True, help_text='Optional: link to company website')),
                ('location', models.CharField(blank=True, help_text='City or remote', max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('current', models.BooleanField(default=False, help_text='Check if this is your current position')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Detailed role description')),
                ('achievements', models.JSONField(blank=True, default=list, help_text='List of key achievements or responsibilities')),
                ('technologies', models.JSONField(blank=True, default=list, help_text='List of tools, languages, or frameworks used')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experiences',
                'ordering': ['-start_date', 'order'],
            },
        ),
    ]
