# Generated by Django 5.2.7 on 2025-10-22 17:45

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Detailed description of the project')),
                ('role', models.CharField(blank=True, help_text='Your role in this project, e.g., Developer, QA, Designer', max_length=100)),
                ('owner', models.CharField(blank=True, help_text='Project owner or company name', max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='projects/')),
                ('technologies', models.JSONField(blank=True, default=list, help_text='List of technologies used')),
                ('github_url', models.URLField(blank=True)),
                ('live_url', models.URLField(blank=True)),
                ('featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
