# Generated by Django 5.2.7 on 2025-10-24 02:21

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_contactmessage_publication_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Detailed description of the project', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='live_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.CharField(blank=True, help_text='Project owner or company name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='role',
            field=models.CharField(blank=True, help_text='Your role in this project, e.g., Developer, QA, Designer', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.JSONField(blank=True, default=list, help_text='List of technologies used', null=True),
        ),
    ]
