# Generated by Django 5.2.7 on 2025-10-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_project_description_alter_project_github_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(help_text='Degree or certification name, e.g., B.Sc. in Computer Science', max_length=200)),
                ('institution', models.CharField(blank=True, help_text='Name of the educational institution', max_length=200, null=True)),
                ('location', models.CharField(blank=True, help_text='City or location of the institution', max_length=100, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, help_text='Additional details about the education', null=True)),
            ],
        ),
    ]
