# Generated by Django 5.2.7 on 2025-10-25 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_certification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certification',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='certification',
            name='issue_date',
        ),
    ]
