# Generated by Django 5.2.7 on 2025-11-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_certification_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.CharField(blank=True, help_text='Optional: store icon class (e.g. fa-python, devicon-django-plain)', max_length=255),
        ),
    ]
