# Generated by Django 5.2.7 on 2025-11-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_skill_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='business_value',
            field=models.TextField(blank=True, help_text='Business value or impact of the project', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='duration',
            field=models.CharField(blank=True, help_text='Project duration, e.g., Jan 2022 - Jun 2022', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, help_text='Project status, e.g., Completed, Ongoing', max_length=50, null=True),
        ),
    ]
